### ISSUE TITLE
Example not working on Mojave, Xcode 10.0

### ISSUE THREAD

**Issue by adamski** [JanosGit/OpenGLRealtimeVisualization4JUCE#1]
I'm trying to the run the example using Xcode 10 on macOS Mojave. The main UI displays, but no visualisations. Anything that might be missing?

**Comment by JanosGit** [comment]
I haven't updated my Mac to Mojave so far but I'll continue working on the project in the next days. Will have a look at it soon. Just for clarification, is there any line drawn and can you verify that there actually is some audio coming in? Thanks for your feedback!

**Comment by adamski** [comment]
I've verified that the audio device has been set up correctly i.e. gets the buffer size etc. I've not actually verified that audio is coming in but other JUCE audio apps are working on my system. I can see the background grid, but no lines related to the visualisation.

**Comment by CrushedPixel** [comment]
I have the same issue.
This seems to be related to Mojave's new permission system - in the console, I get the following error:
```
2019-01-15 00:18:29.447547+0100 StandaloneOscilloscopeSpectralAnalyzer[19950:841837] SecTaskLoadEntitlements failed error=22 cs_flags=20, pid=19950
2019-01-15 00:18:29.447661+0100 StandaloneOscilloscopeSpectralAnalyzer[19950:841837] SecTaskCopyDebugDescription: StandaloneOscill[19950]/0#-1 LF=0
```

I'm currently investigating what part of the application causes this.

**Comment by CrushedPixel** [comment]
This seems to be related to:
https://forum.juce.com/t/osx-mojave-openglcontext-attachto-issue-if-more-than-one-context-is-used/31055

> The issue comes with OSX Mojave where the VST3 plugin within the JUCE AudioPluginHost as well as the Standalone Application blocks rendering of the components completely as soon as more than one OpenGLContext is active.
> All plugin formats do work in Reaper64, Cubase and Pro Tools but show rendering issues on an intermittent basis.

In short, rendering two OpenGL components at the same time does not work with the specific Mojave version we happen to use - I'll update now and will report back.

**Comment by CrushedPixel** [comment]
Indeed, updating to macOS Version 10.14.2 fixed the issue - The example app runs just fine now!

**Comment by JanosGit** [comment]
Thank you for investigating, in fact I'm a bit reclutant in updating my development machine to Mojave while being in the middle of some time sensitive development task. However this drastically raises the priority of the plan to use a shared context for scenarios with multiple Components in one application, which if I understood it right should fix the problem for people that are still working on a Mac OS version < 10.14.2?

**Comment by CrushedPixel** [comment]
Yes, as my investigations showed, only displaying one component at a time worked just fine on 10.14.1.
Note that this is not too big of an issue though, as only macOS Versions 10.14.0 and 10.14.1 are affected AFAIK, and the system update has been out for a while now, so IMO you don't need to prioritize it unless it has other advantages.

**Comment by JanosGit** [comment]
Beneath fixing the bug for those Mac OS versions it should enhance performance to only use a single context in an application, that was the primary reason for me to implement it.

I pushed a first implementation on a new SharedGLContextDev branch. @adamski Have you already updated your system? If not I'd be curious to hear if this implementation fixes the issue you experienced.

**Comment by adamski** [comment]
FYI I updated from git and ran it again this morning, and still got no lines showing. I suspect it needs to ask for mic permissions as that's a requirement now on Mojave? 

<img width="800" alt="screenshot 2019-01-17 at 08 43 08" src="https://user-images.githubusercontent.com/14980/51328624-b3179200-1a6b-11e9-8fe6-01ebbe0e292e.png">

**Comment by CrushedPixel** [comment]
When resizing the window, does the app freeze? That's a solid indicator the OpenGL thread is deadlocked as it was for me.

I had no permissions issue.

**Comment by JanosGit** [comment]
@adamski That's strange. Just to be double sure, you pulled from the SharedGLContextDev branch, not from the master and got those results?

**Comment by adamski** [comment]
Just to update this issue, its still a problem (pulled fresh from master) but compiling for iOS it runs great.

**Comment by l16i** [comment]
@adamski adding the following code at the beginning of `MainComponent()` fixed this issue.

```
auto microphonePermission = RuntimePermissions::recordAudio;
  auto permissionCallback = [this] (bool wasGranted) {
    if(!wasGranted) {
      // Handle no permission here.
    }
  };
  RuntimePermissions::request(microphonePermission, permissionCallback);
```

I also added the `Privacy - Microphone Usage Description` key in the info.plist file.

**Comment by adamski** [comment]
Ah thanks @laurentNoudohounsi - that makes sense.

**Comment by JanosGit** [comment]
Thanks @laurentNoudohounsi - I thought that it was obvious that microphone access has to be granted when working with Mojave and did not consider it to be the source of the error reported here. However, I just pushed a commit that now includes the permission request. Really glad that this solves the issue :)
